version: 2
jobs:
  build:
    docker:
      - image: eldesh/coq:8.9.0
    steps:
      - checkout
      - run: |
          source ~/.profile
          ./configure.sh
          make html
      - run: |
#          cp -r statics/* html/
          cp html/Main.html html/index.html
      - persist_to_workspace:
          root: html
          paths: .
  docs-deploy:
    docker:
          - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: html
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@example.com"
            git config user.name "ci-build"
      - run: ls -la
      - add_ssh_keys:
          fingerprints:
            - "17:9a:e2:82:98:76:7d:60:31:cd:13:67:65:58:09:4c"
      - run:
          name: Deploy docs to master branch
          command: gh-pages --message "[skip ci] doc upload" --branch master --dist html

workflows:
  version: 2
  build:
    jobs:
      - build
      - docs-deploy:
          requires:
            - build
          filters:
            branches:
              only: source
